### ISSUE TITLE
Call for Sponsors Submit Button is Green Not Pink

### ISSUE THREAD

**Issue by kingkool68** [wcus/wcus-2023#1]
The submit button on the Call for Sponsors page is green while the Figma comps all show pink buttons. See https://us.wordcamp.org/2023/call-for-sponsors/

Comp: https://www.figma.com/file/UPj7YVn6LUKVG15a4fWz7E/WCUS-2023?node-id=715-1065&t=tT0CJZQAB1uydMmX-0 

![Screenshot 2023-04-17 at 10 17 37 AM](https://user-images.githubusercontent.com/867430/232513432-af8d510b-f686-4e2e-864b-277419d8aa5d.jpg)

**Comment by ryelle** [comment]
This was the result of a setting on the form itself, so I've updated the page & the button is the default pink color again.

<img width="686" alt="Screenshot 2023-04-17 at 1 02 52 PM" src="https://user-images.githubusercontent.com/541093/232558057-34e362e3-83cf-4a1b-84b8-d0c6863880ae.png">
